services:
  postgres-db:
    image: postgres:13.20-alpine3.20
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todo-api:
    build: ./backend
    container_name: todo-api
    environment:
      DATABASE_URL: jdbc:postgresql://postgres-db:5432/todo_db
      DATABASE_USER: todo_user
      DATABASE_PASSWORD: todo_password
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"

  todo-frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:80"
    depends_on:
      - todo-api

volumes:
  todo_pgdata:
