version: "3.8"
services:
  postgres-db:
    image: postgres:13.20-alpine3.20
    container_name: todo_postgres
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todo-api:
    build: ./todo-backend
    container_name: todo_api
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://todo_user:todo_password@postgres-db:5432/todo_db
    ports:
      - "8080:8080"

  todo-frontend:
    build: ./todo-frontend
    container_name: todo_frontend
    depends_on:
      - todo-api
    ports:
      - "3000:3000"

volumes:
  todo_pgdata:
